# Generated by Django 4.1 on 2023-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0002_utmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='utype',
            field=models.CharField(default='Patient', max_length=10),
        ),
    ]
