# Generated by Django 4.1 on 2023-04-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0003_signupmodel_utype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('Patient', 'PATIENT'), ('Doctor', 'DOCTOR')], default='Patient', max_length=20)),
                ('uname', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UTModel',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='utype',
        ),
    ]
