# Generated by Django 4.1 on 2023-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0004_usertypemodel_delete_utmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertypemodel',
            name='uname',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='utype',
            field=models.CharField(default='Patient', max_length=100),
        ),
    ]
