# Generated by Django 4.1 on 2023-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0005_remove_usertypemodel_uname_signupmodel_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='utype',
            field=models.CharField(max_length=10),
        ),
    ]
